[project]
name = "calgebra"
version = "0.2.2"
description = "A tiny DSL for calendar interval algebra - compose, filter, and query time ranges using set operations."
authors = [{ name = "ashenfad"}]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
keywords = ["calendar", "scheduling", "intervals", "time", "algebra", "dsl"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Office/Business :: Scheduling",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
    "python-dateutil>=2.8.0",
    "typing-extensions>=4.0.0",
]

[project.urls]
"Homepage" = "https://github.com/ashenfad/calgebra"
"Bug Tracker" = "https://github.com/ashenfad/calgebra/issues"
"Documentation" = "https://github.com/ashenfad/calgebra#readme"
"Source" = "https://github.com/ashenfad/calgebra"

[project.optional-dependencies]
dev = [
    "ruff",
    "black",
    "uv",
    "pytest",
    "gcsa>=2.6.0",
]
google-calendar = [
    "gcsa>=2.6.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {exclude = ["tests*", "build*"]}}

# Include documentation files within the package
[tool.setuptools.package-data]
calgebra = ["docs/*.md", "py.typed"]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
